### ISSUE TITLE
Estrutura para links que precisam ser traduzidos

### ISSUE THREAD

**Issue by nicholasess** [netcoders/DevTranslators#1]
Galera, pensei nessa estrutura.

Já que o MDN já tem a estrutura de links, podemos seguir a mesma coisa.
### JavaScript
-  [Guia JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide)
  - [Introdução](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Introduction)
    ...

E conforme for traduzindo, só mandarem um PR atualizando a lista com um Ok ao lado
-  [Guia JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide) - OK

Que tal?

**Comment by ErickWendel** [comment]
acho que precisamos fazer um esquema, pra nenhum atropelar o outro. Pensei em até criar um trello, para a galera ir arrastando para as categorias de quando está fazendo, para revisão e para completo, ai eu vou registrando aqui.

pensei tambem em fazer com issues, abrir varias issues e conforme vao fazendo, vamos atualizando a lista com o nome de quem fez, para ajudar tambem a galera que está contribuindo

**Comment by nicholasess** [comment]
Siim, pensei na possibilidade do Trello, mas como não somos responsáveis pelo MDN em si, podemos gerenciar tanto do Trello, quanto pelas issues.
É que o Trello é mais dinâmico.

**Comment by limup** [comment]
Bacana!!

Atenciosamente,

Arnaldo Junior

Cel: 9 8724-1583

Enviado pelo Outlook para Android

On Wed, Jul 29, 2015 at 10:14 AM -0700, "Nicholas Eduardo" notifications@github.com wrote:
Galera, pensei nessa estrutura.

Já que o MDN já tem a estrutura de links, podemos seguir a mesma coisa.

## Links para tradução

### JavaScript
-  [Guia JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide)
  - [Introdução](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Introduction)
    ...

E conforme for traduzindo, só mandarem um PR atualizando a lista com um Ok ao lado
-  [Guia JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide) - OK

Que tal?

---

Reply to this email directly or view it on GitHub:
https://github.com/netcoders/DevTranslators/issues/1

**Comment by ErickWendel** [comment]
Então, vamos gerenciar pelas issues aqui no github. Vou listar amanha todos os links e adicionar nas issues pra galera ir traduzindo e revisando.

Vamos mudar o futuro da web galera o/

**Comment by nicholasess** [comment]
Qual será o padrão nas issues?
ex:JavaScript Guide?

**Comment by mauricionr** [comment]
BOra traduizir, Vão ser lugares especificos? MDN, MSDN, YDN??

**Comment by ghost** [comment]
Acho o Trello uma ótima ideia. Agiliza todo o processo.

**Comment by ghost** [comment]
Oi pessoal! Uma pergunta: Alguém já postou material para ser traduzido?

**Comment by omatheusantana** [comment]
Também quero saber.

_Atenciosamente,_
_Matheus Oliveira_
_(61) 8288-0470 *
*(61) *_9302-2900*
_---------------------------------------------------------------------------_
*"Somos o que fazemos para mudar o que fomos" *
- Rosa de Saron - Velhos Outonos*
  _---------------------------------------------------------------------------_

2015-08-21 14:52 GMT-03:00 Thiago Piza notifications@github.com:

**Comment by ghost** [comment]
Pessoal, vou sair de férias por uma semana. Nesse período vou ficar offline. Mas quando voltar estarei pronto para colaborar nas traduções e no que for necessário. Um grande abraço a todos e até breve.
